use_default_settings: true

server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "${RANDOM_STRING_60}" # 请随意修改这一串字符
  api_key: "${SEARXNG_API_KEY}"

search:
  formats:
    - html
    - json # 关键：必须开启 json，大模型才能读取
